defaults: &defaults
  admin:
    email:    admin@example.com
    password: admin12345

  pagination: 10

  fake_records:
    count: 20

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
